import type { Metadata } from 'next'
import ThemeButton from '../components/theme-button'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className="flex flex-col min-h-screen">
      <div className="fixed z-10 top-1 left-1">
        <ThemeButton />
      </div>
      <div className="flex-grow">{children}</div>
    </div>
  )
}
